#######################
# Theme Customization #
#######################

title: Hyewon,Lim                            # used in <title> tag & site header
author: Hye won LIM                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Hello 911 emergency, there's a handsome guy in my house!
  Oh wait a second, cancel that. It's only me.
slogan: It's me!                          # used in site header, beside title
avatar: /i/dog.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/rlue/jekyll-solana # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Intro
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/limenow
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
Projects:
  - title: OSS class.. I LOVE IT!
    teaser: I learn many things with many labs.
    url: https://github.com/rlue/jekyll-solana
    role: First
    category: Frontend Dev
  - title: Play with my dog..LOVE IT!
    teaser: A talking robot. Now available on Google Play?
    url: https://play.google.com/store/apps/details?id=com.microsoft.cortana
    role: Second
    category: NLP
  - title: Trip to somewhere!
    teaser: I've been America, Singapore, Taiwan, Phillipines, Saipan, Borakai(The most beautiful).
    url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
    role: Third
    category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
